<?php
$mailsetters=array();
$mailsetters['host']='sg2plcpnl0030.prod.sin2.secureserver.net';
$mailsetters['smtpauth']=true;
$mailsetters['smtpdebug']=0;
$mailsetters['port']='465';
$mailsetters['username']='booking@clickmybooking.com';
$mailsetters['password']='Sanjaya1987';
$mailsetters['smtpsecure']='ssl';
$mailsetters['from']='booking@clickmybooking.com';
$mailsetters['fromname']='Clickmybooking';
$mailsetters['adminmail']='raj@clickmybooking.com';
//$mailsetters['adminmail']='smithhappy123@gmail.com';